// <auto-generated />
using AspNetCoreWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspNetCoreWebApi.Migrations
{
    [DbContext(typeof(CompContext))]
    [Migration("20171026034302_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreWebApi.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CamperId");

                    b.Property<string>("Country");

                    b.Property<string>("Province");

                    b.Property<string>("StreetName");

                    b.HasKey("AddressId");

                    b.HasIndex("CamperId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("AspNetCoreWebApi.Models.Camper", b =>
                {
                    b.Property<int>("CamperId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName");

                    b.HasKey("CamperId");

                    b.ToTable("Campers");
                });

            modelBuilder.Entity("AspNetCoreWebApi.Models.Address", b =>
                {
                    b.HasOne("AspNetCoreWebApi.Models.Camper", "Camper")
                        .WithMany("Addresses")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
